# Generated by Django 6.0.1 on 2026-02-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightlog',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='activity_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='meal_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='posture_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='WeightLog',
        ),
    ]
