# Generated by Django 6.0.3 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options_alter_user_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estimated_body_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]