# Generated by Django 6.0.3 on 2026-04-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_diet_plan_user_plan_history_user_idx_diet_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan_history',
        ),
    ]
