# Generated by Django 6.0.1 on 2026-05-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_plan_history'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='idx_fitness_profile',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_active_plan',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_weight_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_activity_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_meal_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_posture_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_diet_plan',
        ),
        migrations.AlterField(
            model_name='gymlog',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['fitness_profile'], name='idx_fitness_profile'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['active_plan'], name='idx_active_plan'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['diet_plan'], name='idx_diet_plan'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['weight_logs'], name='idx_weight_logs'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['activity_logs'], name='idx_activity_logs'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['meal_logs'], name='idx_meal_logs'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['posture_logs'], name='idx_posture_logs'),
        ),
    ]
