# Generated by Django 6.0.1 on 2026-05-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_plan_history'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='idx_fitness_profile',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_active_plan',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_weight_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_activity_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_meal_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_posture_logs',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_diet_plan',
        ),
        migrations.AlterField(
            model_name='gymlog',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
